model_parameters:
    model_name: "Qwen/Qwen3-0.6B"
    dtype: "float16"
    batch_size: 1
    max_length: 1024
    trust_remote_code: False        # default
    add_special_tokens: True        # default
    skip_special_tokens: True       # default
    compile: False                  # default
    pairwise_tokenization: False    # default
    continuous_batching: False      # default
    generation_parameters:
        presence_penalty: 0.0
        repetition_penalty: 1.0
        frequency_penalty: 0.0
        temperature: 0.0 # greedy for stable evaluation, recomended: 0.7
        top_k: 20
        min_p: 0.0
        top_p: 0.8
        seed: 42
        stop_tokens: null
        max_new_tokens: 256
        min_new_tokens: 0
